-- auto-generated definition
create table account
(
    id         bigint generated by default as identity
        primary key,
    email      varchar(255)
        constraint uniqueemail
            unique,
    first_name varchar(255),
    last_name  varchar(255),
    password   varchar(255),
    role       varchar(255)
);

alter table account
    owner to postgres;

-- auto-generated definition
create table burger
(
    id          bigint generated by default as identity
        primary key,
    created_at  timestamp,
    description varchar(255),
    name        varchar(255),
    price       integer,
    type        varchar(255),
    author_id   bigint
        constraint fk7lab8ctnr4icu8ohhjdsqtv7b
            references account
);

alter table burger
    owner to postgres;

-- auto-generated definition
create table ingredient
(
    id    bigint generated by default as identity
        primary key,
    name  varchar(255),
    price integer,
    type  varchar(255)
);

alter table ingredient
    owner to postgres;

-- auto-generated definition
create table burger_ingredient
(
    burger_id     bigint not null
        constraint fkdqlgnllbd1ey0mos6gy60d45l
            references burger,
    ingredient_id bigint not null
        constraint fk1dsqnsuwv510eu83kiqvh1b2n
            references ingredient
);

alter table burger_ingredient
    owner to postgres;

-- auto-generated definition
create table burger_order
(
    id        bigint generated by default as identity
        primary key,
    placed_at timestamp,
    status    varchar(255),
    user_id   bigint
        constraint fk37vjx73pdw2ms1ifj5l8jkq7k
            references account
);

alter table burger_order
    owner to postgres;

-- auto-generated definition
create table burger_order_burgers
(
    order_id  bigint not null
        constraint fkgul2nm513qj9iwxmbf023vq5i
            references burger_order,
    burger_id bigint not null
        constraint fkgtkas6ybxvvkyo7kgxtn0xs28
            references burger
);

alter table burger_order_burgers
    owner to postgres;

-- auto-generated definition
create table comment
(
    id         bigint generated by default as identity
        primary key,
    created_at timestamp,
    text       varchar(255),
    author_id  bigint
        constraint fkrv3ioi1asorsx190lfsdnkw19
            references account,
    burger_id  bigint
        constraint fks7awk729eveey06ed7vrgt7yk
            references burger
);

alter table comment
    owner to postgres;


INSERT INTO ingredient (id, name, price, type) VALUES (1, 'Котлета из мраморной говядины', 220, 'PROTEIN');
INSERT INTO ingredient (id, name, price, type) VALUES (3, 'Томаты', 20, 'VEGGIES');
INSERT INTO ingredient (id, name, price, type) VALUES (4, 'Чеддер', 30, 'CHEESE');
INSERT INTO ingredient (id, name, price, type) VALUES (5, 'Горчица', 10, 'SAUCE');
INSERT INTO ingredient (id, name, price, type) VALUES (2, 'Булочка', 20, 'WRAP');
